### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by mycaule** [Chalarangelo/30-seconds-of-code#311] opened 2017-12-22 08:23 UTC
It could be great to have unit tests for the small functions you wrote.

There are also dynamic documentation generators. 
In Scala we have: https://github.com/tpolecat/tut

I don't know if there is similar in Javascript.

**Comment by Chalarangelo** [comment] 2017-12-22 08:25
Duplicate of #78, so I'm closing, comment under that issue if you have suggestions about this topic. We are not currently working on this actively, but we are hoping to add tests in the next few months.

**Comment by mycaule** [comment] 2017-12-22 08:26
Ok no problem, thanks for this awesome repo!

**Closed** 2017-12-22 08:27 UTC
